apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-rag

commonLabels:
  app.kubernetes.io/part-of: nexus-rag
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - gateway-deployment.yaml
  - data-api-deployment.yaml
  - ui-deployment.yaml
  - mongodb-statefulset.yaml
  - redis-statefulset.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml
  - pvc.yaml
  - pdb.yaml
  - networkpolicy.yaml
