apiVersion: v1
kind: Service
metadata:
  name: nexus-gateway
  namespace: nexus-rag
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: nexus-rag
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-data-api
  namespace: nexus-rag
  labels:
    app.kubernetes.io/name: data-api
    app.kubernetes.io/part-of: nexus-rag
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: data-api
  ports:
    - port: 3456
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-ui
  namespace: nexus-rag
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: nexus-rag
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ui
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-mongodb
  namespace: nexus-rag
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: nexus-rag
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - port: 27017
      targetPort: mongo
      protocol: TCP
      name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-redis
  namespace: nexus-rag
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: nexus-rag
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
